Data source organization
eea/eea.coremetadata pull request #25
Opened 2023-09-28 11:27 UTC by dobri1408

2023-10-12 18:03 UTC, avoinea requested changes

2023-10-12 18:03 UTC, avoinea commented on eea/coremetadata/indexer.py
> +def DataProvenanceIdexer(obj):
Also, in python, we don't use CamelCase for methods, it should be `lowercase with words separated by underscores as necessary to improve readability.` See "PEP8 guidelines":https://peps.python.org/pep-0008/#method-names-and-instance-variables

2023-10-13 06:48 UTC, dobri1408 commented
Hi @avoinea I have fixed what you requested.

2023-10-16 14:14 UTC, avoinea approved these changes

2023-10-16 14:15 UTC, merged