Fix: preview image fields appear in between EEA core metadata.
eea/eea.coremetadata pull request #9
Opened 2022-08-03 12:08 UTC by dobri1408

2022-08-05 07:14 UTC, nileshgulia1 requested changes
@dobri1408 The title and description should not come under EEA core metadata behavior, instead should be in default.
![Screenshot 2022-08-05 at 12 40 41 PM](https://user-images.githubusercontent.com/22280901/183022768-503bbe15-e6e9-484a-a4ee-d73015405f16.png)

2022-08-10 12:24 UTC, Petchesi-Iulian requested changes
When testing these changes I had the following error come up:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 266, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module plone.rest.service, line 22, in __call__
  Module plone.restapi.services, line 19, in render
  Module plone.restapi.services.content.get, line 16, in reply
  Module plone.restapi.serializer.dxcontent, line 102, in __call__
  Module plone.restapi.serializer.dxfields, line 82, in __call__
  Module zope.schema.vocabulary, line 194, in getTerm
TypeError: unhashable type: 'list'

If I removed the [] around DEFAULT_PUBLISHER/ORGANISATIONS then the error was gone and I was able to edit an object via volto.

2022-08-10 15:30 UTC, Petchesi-Iulian approved these changes
lgtm

2022-08-11 06:43 UTC, nileshgulia1 approved these changes

2022-08-11 06:43 UTC, merged